### ISSUE TITLE
Rise Media Player from Windows Store Crashes On Launch

### ISSUE THREAD

**Issue by joshua106ful** [josephbeattie/Fluent-Media-Player-Dev#108]
I installed Rise from the windows store, and it looks like it installed successfully but when it launches, it crashes and brings up this notification:
Unfortunately, Rise Media Player crashed. Click to view stack trace.
I've uninstalled and installed it again, but the same problem happens.

**Comment by josephbeattie** [comment]
Click the notification. It will show more info about the error. Please send a screenshot of that error please :)

**Comment by joshua106ful** [comment]
I clicked on the notification, but it just relaunches the app and the same thing happens again. Here is a screenshot of what happens, the picture is on this word document.
[Screenshot.docx](https://github.com/Rise-Software/Rise-Media-Player/files/7818189/Screenshot.docx)

**Comment by itsWindows11** [comment]
@joshua106ful use the built in upload image feature instead, I can't view docx files rn.
![image](https://user-images.githubusercontent.com/81253203/148352812-2206fe47-cf48-4181-a98f-6f32ef9893f6.jpg)
oh btw i couldn't reproduce the issue.

**Comment by joshua106ful** [comment]
![Picture1](https://user-images.githubusercontent.com/97199255/148460646-0dc62fb1-fe81-499b-9696-677b5f111621.png)
I took this screenshot right before the application closes. This is the first time this has happened to me, I stopped getting the other error that has trouble installing Rise Media Player.

**Comment by josephbeattie** [comment]
Windows build? Most people using the store version have not had this issue. It’s curious

**Comment by joshua106ful** [comment]
I'm on Windows 11 build 22000.376

**Comment by josephbeattie** [comment]
Yeah thats really strange. I’m not sure what more we can do besides ask you to crash the app again, then show the information in Event Viewer.

**Comment by joshua106ful** [comment]
![Picture3](https://user-images.githubusercontent.com/97199255/148462725-31606fb5-b102-4529-a9da-dc7762680fc1.png)
![Picture2](https://user-images.githubusercontent.com/97199255/148462727-1cd6a1f8-6dff-4d61-82d0-af956eda13d9.png)
![Picture1](https://user-images.githubusercontent.com/97199255/148462728-fcef9011-10b5-4b85-b7e9-ae652088454b.png)

This is what comes up in Event Viewer.
