### ISSUE TITLE
Storing user tokens in AppData

### ISSUE THREAD

**Issue by yoshiask** [josephbeattie/Fluent-Media-Player-Dev#117]
I noticed that the commit adding Last.fm support saves the user's token information in an XML file in AppData. This is a bad idea, as it's accessible to other potentially malicious programs that can read this folder freely.

The proper way to store access and refresh tokens is to use UWP's [credential locker](https://docs.microsoft.com/en-us/windows/uwp/security/credential-locker).

**Comment by josephbeattie** [comment]
This is only a temporary solution, please don’t worry. We will ensure this data is protected once we release to insiders. All GitHub users, use at your own risk

**Comment by josephbeattie** [comment]
Do you have a Discord?

**Comment by josephbeattie** [comment]
Im dumb

**Comment by rounk-ctrl** [comment]
fixed in latest commit
