### ISSUE TITLE
Opening .mp3 files crash the player

### ISSUE THREAD

**Issue by LoadingName1386** [josephbeattie/Fluent-Media-Player-Dev#124]
### Description

When I try to open a .mp3 file, the media player just open for a small amount of time and then crash. To be clear, .mp4 files work just fine, it is just the mp3 files. Moreover, the media player just won't update new songs added to the music folder

https://user-images.githubusercontent.com/98937364/154798260-c138d7e9-a982-4cd2-b182-3054b4f22894.mp4

### Expected behavior

Being able to play .mp3 files and see the updated files through the media player

### Rise Media Player Version

Alpha Preview 1 Ver 0.0.160.0

### Windows Version

Windows 11 Dev ni-release 22557

### Relevant Assets/Logs

https://user-images.githubusercontent.com/98937364/154798373-729dbabe-5c6f-48b0-b8ce-d67b30fe063e.mp4

**Comment by nimsandu** [comment]
same happens
