### ISSUE TITLE
Add support for webnowplaying in Rainmeter

### ISSUE THREAD

**Issue by LoadingName1386** [josephbeattie/Fluent-Media-Player-Dev#125]
### Solution/Idea

Add support for rainmeter to display song info in rainmeter skins

### Alternatives

Maybe use the same plugin that the old window media player use

### Rise Media Player Version

Alpha Preview 0.0.160.0

### Windows Version

Windows 11 Dev 22557

**Comment by itsWindows11** [comment]
I don't think that's possible because of how limited UWP is.
