### ISSUE TITLE
BSOD when pinning the program

### ISSUE THREAD

**Issue by MasterPro3007** [josephbeattie/Fluent-Media-Player-Dev#126]
### Description

Hello, I BSOD when pinning the app to the taskbar with the compiled app, i compiled the app in visual studio 2022.
Who can help me?

### Steps To Reproduce

1. Open the app
2. Pin the app to the taskbar
3. and then will BSOD

### Expected behavior

I searched in youtube and I reviewed it's a bug of the video graphic of the program (the icon of the program BSOD my PC)

### Rise Media Player Version

Rise-Media-Player-0.0.160.0

### Windows Version

Windows 11 21H2 (build 22000.493)

### Relevant Assets/Logs

Bsod with KERNEL_MODE_HEAP_CORRUPTION of origin Kernel_Power

**Comment by itsWindows11** [comment]
Closed due to being unrelated to RiseMP, also btw this isn't the right place to ask for BSOD diagnostics.
