### ISSUE TITLE
Sorting songs inside an album by disc/track # rather than just track # for multi-disc albums

### ISSUE THREAD

**Issue by silentgurdian** [josephbeattie/Fluent-Media-Player-Dev#128]
### What's the Problem?

In case of albums with more than one discs, the tracks are sorted by track #. As a result the first track off of the first and second disc in a 2Disc CD would show up one after the other. In the correct scenario the tracks from the first disc should be listed, and then the tracks from the second disc and so on. (Note: The disc # and track # are both populated in the tags of my tracks, hence the request).

### Solution/Idea

Use both the track# and disc # tag to sort the albums with the hierarchy of disc# > tag#.

### Alternatives

.

### Rise Media Player Version

Pre-Alpha 4 - v0.0.14.0

### Windows Version

Windows 11 21H2 22000.527

**Comment by yourordinarycat** [comment]
Fixed in #222
