### ISSUE TITLE
bug in short

### ISSUE THREAD

**Issue by Xer0s13** [josephbeattie/Fluent-Media-Player-Dev#130]
### Description

classifying presents problems. I configure it and when I close the application the configurations are deleted.

### Steps To Reproduce

1 I open the program, 2 I change the order of the songs, 3 I close the program and open it again and the filters are reset.

### Expected behavior

that my settings will be saved even if I close the program.

### Rise Media Player Version

Pre-Alpha 4 - v0.0.14.0

### Windows Version

windows 11 21H2 22000.527

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/40452486/155900310-c0286b29-67c6-41f9-94a0-e96c8b1226ed.png)

**Comment by itsWindows11** [comment]
I don't think these are still functional yet

**Comment by yourordinarycat** [comment]
Fixed in #222
