### ISSUE TITLE
Being able to join to an SRT server

### ISSUE THREAD

**Issue by BobbyESP** [josephbeattie/Fluent-Media-Player-Dev#139]
### What's the Problem?

No, there's no problem related

### Solution/Idea

Adding the ability to join to an srt server as VLC.

### Alternatives

I' ve considered still using VLC Player for that use but still using Rise Media Player for others.

### Rise Media Player Version

Pre-Alpha 4 - v0.0.14.0

### Windows Version

Windows 11 Home // 1000.22000.527.0

**Comment by josephbeattie** [comment]
Hey! we have plans to support such features :) - By the way, you’re running an older version of the app it seems. Are you running Alpha 1 Preview? If not, I’d suggest you update. Alpha 2 Preview is coming very soon :)

**Comment by BobbyESP** [comment]
Okk, nice!
