### ISSUE TITLE
Video and Image Files

### ISSUE THREAD

**Issue by sumeshir26** [josephbeattie/Fluent-Media-Player-Dev#15]
It would be great if this would support other file types exept for audio ones.

**Comment by josephbeattie** [comment]
Hey! We have plans to support videos. Photos will not be coming as there are already much better photo viewers and editors available (like the Windows 11 photos app which also has WinUI 2.6/2.7). Thanks for your comment :)

**Comment by sumeshir26** [comment]
Yeah, the Windows 11 photos app is really good. But in the long term, it would be good if there was only one app that could display all files types, something like the Windows Media Player.
Great work!
