### ISSUE TITLE
Msix Package Installation Failed

### ISSUE THREAD

**Issue by kel456** [josephbeattie/Fluent-Media-Player-Dev#151]
### Description

After installing the certificate, I tried installing the msix package. However, there was there error message: 
App installation failed with error message: Access is denied. (0x80070005)

### Steps To Reproduce

1. Install certificate using instructions listed in readme
2. Double click msix package to install
3. Installation failed error appears after a few seconds

### Expected behavior

I expected Rise Media Player to update properly without errors. 

### Rise Media Player Version

v0.0.135.0

### Windows Version

Windows 11 22000.556

### Relevant Assets/Logs

![installation failed](https://user-images.githubusercontent.com/99143964/158000301-552f725c-de8a-465c-8e1a-57c726019274.png)

**Comment by josephbeattie** [comment]
If you are updating, this is normal. Reinstall the app. This is by no means a bug and we always suggest you reinstall, especially at this stage.

**Comment by kel456** [comment]
I have uninstalled the one I have then reinstalled, but the issue persists.
