### ISSUE TITLE
Crash while fetching artist pictures on Artists page

### ISSUE THREAD

**Issue by LolicoreExpress** [josephbeattie/Fluent-Media-Player-Dev#163]
### Description

RiseMP seems to crash consistently when I go on the Artists page and it starts automatically fetching artist profile pictures from the web.  It fetches some and then stops at the same point everytime, hangs for a bit, and crashes.

### Expected behavior

No crashes 😅

### Rise Media Player Version

Alpha Preview 2 v0.0.170.0

### Windows Version

Windows 11 22H2 22593.1

### Relevant Assets/Logs

https://user-images.githubusercontent.com/29737484/162225860-84b5c500-4690-4dd7-a1e5-eb5bfbc541b4.mp4

**Comment by itsWindows11** [comment]
Should be fixed by next release.
