### ISSUE TITLE
Dragging on the music bar doesn't do anything

### ISSUE THREAD

**Issue by kurushimee** [josephbeattie/Fluent-Media-Player-Dev#169]
### Description

If you just click and release at any point in the music it skips to that moment, but if you click and drag, music doesn't follow the cursor and the music bar indicator teleports back and forth from current position it is playing at and the position of the cursor when you move the cursor (if you stop - it stays at the current position it is playing at).

### Steps To Reproduce

1. Play any music
2. Click and drag on the music bar
3. Music doesn't follow cursor's position

### Expected behavior

Music follows cursor and plays from the selected position

### Rise Media Player Version

Alpha Preview 2 v0.0.171.0

### Windows Version

Windows 11 21H2 22000.652

### Relevant Assets/Logs

![(Cursor is still held down on the bar)](https://user-images.githubusercontent.com/81345597/167682278-8455d2c9-e80f-423c-9413-f0163d6c94de.png)

**Comment by itsWindows11** [comment]
Should be already fixed in #164.
