### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by TechHopGitHub** [josephbeattie/Fluent-Media-Player-Dev#170]
### Description

The installer won't even let me install. Here is the error message:
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

### Steps To Reproduce

run the installer and not have a certificate..

### Expected behavior

I thought it would let me Install

### Rise Media Player Version

Latest at time of posting (v0.0.171.0)

### Windows Version

Windows 11 22000.675

### Relevant Assets/Logs

Non Applicable

**Comment by itsWindows11** [comment]
Take a look at this [section](https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions)

**Comment by TechHopGitHub** [comment]
> Take a look at this [section](https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions)

Didn't help...

**Comment by Nick-h4ck3r** [comment]
> Take a look at this [section](https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions)

It worked, thanks!
