### ISSUE TITLE
Album art showing for all songs in the album

### ISSUE THREAD

**Issue by MSOB7YY** [josephbeattie/Fluent-Media-Player-Dev#178]
### Description

When playing any song it shows the whole album image instead of the song's image.

### Expected behavior

each song has its own album art

### Rise Media Player Version

Alpha Preview 2

### Windows Version

Windows 11 Pro Insider Preview

### Relevant Assets/Logs

.

**Comment by itsWindows11** [comment]
Fixed in #198.
