### ISSUE TITLE
Root Certificate 

### ISSUE THREAD

**Issue by sd-sanad** [josephbeattie/Fluent-Media-Player-Dev#179]
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)
![Unabble to install](https://user-images.githubusercontent.com/95274164/183273016-aeccd305-3554-4d8f-9964-6739318189ea.png)
![Unable To Find It On Windows Store](https://user-images.githubusercontent.com/95274164/183273017-05ae2a5b-c05d-4b58-a392-3bfd80949473.png)

**Comment by yoshiask** [comment]
Have you tried the instructions here on the installer you downloaded?
https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions

Or if you want to use the Microsoft Store:
http://bit.ly/rise-insider

**Comment by Andrew-Sor** [comment]
> Have you tried the instructions here on the installer you downloaded?
> https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions

The link does not lead to any instructions, and the survey is impossible to complete. It says "The maximum number of responses has been reached. Contact the owner of the form to continue."
