### ISSUE TITLE
Crash Details

### ISSUE THREAD

**Issue by BigDan200985** [josephbeattie/Fluent-Media-Player-Dev#180]
The exception System.NullReferenceException happened last time the app was launched.

Stack trace:
Object reference not set to an instance of an object.
   at Rise.App.ChangeTrackers.SongsTracker.<MusicQueryResultChanged>d__2.MoveNext() + 0x249

Source: 
HResult: -2147467261

**Comment by itsWindows11** [comment]
Should be resolved by next release.
