### ISSUE TITLE
"This app package’s publisher certificate could not be verified. (0x800B010A)"

### ISSUE THREAD

**Issue by TF21045** [josephbeattie/Fluent-Media-Player-Dev#188]
### Description

I just want to install this, then I couldn't because of the certificate error I suppose.

### Expected behavior

I am expecting it to install flawlessly.

### Rise Media Player Version

Just installing

### Windows Version

Windows 11 Pro Insider Preview (Beta) v22621.590

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/53613828/189329730-6b581087-8169-4f17-b757-5f6c618f4873.png)

**Comment by itsWindows11** [comment]
See the installation instructions at the bottom of the readme.
