### ISSUE TITLE
Media pauses when pressing space in a text box

### ISSUE THREAD

**Issue by carotteatomique** [josephbeattie/Fluent-Media-Player-Dev#194]
### Description

When pressing the space bar in a text box (for example, when naming a playlist), the media playing in RMP pauses itself.

### Steps To Reproduce

1. Play a media file, such as music
2. Go to "playlists"
3. Create a new playlist
4. When naming the playlist, pressing the space bar will pause the currently playing media

### Expected behavior

Pressing the space bar in a text box would only add a space to the text, not pause the music

### Rise Media Player Version

Alpha Preview 2 - 0.0.170.0

### Windows Version

Windows 11 22H2 22621.521

### Relevant Assets/Logs

https://user-images.githubusercontent.com/87284322/193342398-dda24fb6-6e9e-4645-8566-a2c718c9180e.mp4

**Comment by itsWindows11** [comment]
Will be fixed by next release.
