### ISSUE TITLE
Media player slider not working properly

### ISSUE THREAD

**Issue by uutojtiotewf** [josephbeattie/Fluent-Media-Player-Dev#197]
### Description

I started the song and wanted to rewind it by 2 minutes using the slider. As a result, the slider moved back to the time that it was before the move. Also, while I moved the slider, it moved in different directions

### Expected behavior

I expected that the slider would work without bugs, if you listen to music, then you won’t use this slider, for example, I just turn on and listen to all the songs in a row, but with a video it’s not at all convenient

### Rise Media Player Version

Pre-Alpha 4 v0.0.171.0

### Windows Version

Windows 22H2 22621.674

### Relevant Assets/Logs

Video showing the problem:

https://user-images.githubusercontent.com/115872120/195980794-dbf22e96-90ce-443d-8fe1-9d914540226b.mp4

**Comment by yourordinarycat** [comment]
Fixed in #164
