### ISSUE TITLE
Windows installer blocking installation

### ISSUE THREAD

**Issue by NBKariuki** [josephbeattie/Fluent-Media-Player-Dev#201]
### Description

Upon trying to install the application the following from the Windows Installer shows.

This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

### Expected behavior

Windows to allow installation 

### Rise Media Player Version

Rise Media Player Version: 0.0.171.0

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎29/‎06/‎2022 OS build	22623.746 Experience	Windows Feature Experience Pack 1000.22636.1000.0

### Relevant Assets/Logs

none

**Comment by itsWindows11** [comment]
[Follow the MSIX install instructions](https://github.com/rise-software/rise-media-player#msix-install-instructions)
