### ISSUE TITLE
Totally install fail....

### ISSUE THREAD

**Issue by itsmetoolala** [josephbeattie/Fluent-Media-Player-Dev#208]
### Description

Downloads!

Microsoft:
_We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available._

Github installation prompt:
_The publisher certificate of this app package could not be verified. Contact your system administrator or the app developer to get a new app package with verified certificates. The root certificate and all instant certificates of the signature in the app package must be verified (0x800B010A)_

sad. thought I found a good new mediaplayer...

### Steps To Reproduce

Downloads!

Microsoft:
_We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available._

Github installation prompt:
_The publisher certificate of this app package could not be verified. Contact your system administrator or the app developer to get a new app package with verified certificates. The root certificate and all instant certificates of the signature in the app package must be verified (0x800B010A)_

sad. thought I found a good new mediaplayer...

### Expected behavior

Downloads!

Microsoft:
_We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available._

Github installation prompt:
_The publisher certificate of this app package could not be verified. Contact your system administrator or the app developer to get a new app package with verified certificates. The root certificate and all instant certificates of the signature in the app package must be verified (0x800B010A)_

sad. thought I found a good new mediaplayer...

### Rise Media Player Version

new

### Windows Version

win 11 22h2 new install today

### Relevant Assets/Logs

Downloads!

Microsoft:
_We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available._

Github installation prompt:
_The publisher certificate of this app package could not be verified. Contact your system administrator or the app developer to get a new app package with verified certificates. The root certificate and all instant certificates of the signature in the app package must be verified (0x800B010A)_

sad. thought I found a good new mediaplayer...

**Comment by shrublet** [comment]
You need to install the certificate.
https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions
