### ISSUE TITLE
Sort order of albums

### ISSUE THREAD

**Issue by Crocodile73** [josephbeattie/Fluent-Media-Player-Dev#216]
### Description

The sort order that you choose, does not save for albums. Every time you navigate to artists or songs and back or restarting the app, sort order reverts back to default

### Steps To Reproduce

navigate to albums, sort order by release year and descending.

### Expected behavior

For that sort order to be selected automatically when navigating the app, or restarting

### Rise Media Player Version

Release vnext

### Windows Version

Windows 11 22621.1105

### Relevant Assets/Logs

n/a

**Comment by yourordinarycat** [comment]
Fixed in #222
