### ISSUE TITLE
No reading of ID3Vx tags on SMB Drives

### ISSUE THREAD

**Issue by RG007JM** [josephbeattie/Fluent-Media-Player-Dev#221]
### Description

The app can't read the ID3Vx/FLAC tags that I have on my files stored on a NAS connected via SMB 3.1.1 to my PC.
I can see that the files have the tag, and when I move them to my PC, the app recognizes immediately the tags.
I know that ID3V2.x tags have a bad relationship with streamed files, but even an ID3V1 tag won't be recognized by the app.

### Steps To Reproduce

Get a NAS
Attach it via SMB 3.1.1 to your PC
Select the music folder on your NAS when prompted to choose a music folder on the Rise Media Player App

### Expected behavior

Only the name of the file will be shown, any other info on the metadata will be ignored.

### Rise Media Player Version

Pre-Alpha 2 (v0.0.171.0)

### Windows Version

Windows 11 22H2

### Relevant Assets/Logs

None.

**Comment by itsWindows11** [comment]
Does the file explorer recognize the metadata from that network drive?

**Comment by RG007JM** [comment]
Yes.
![image](https://user-images.githubusercontent.com/53452689/223860741-5deaafe7-079b-416b-a80f-6a1f5050e96b.png)

**Comment by itsWindows11** [comment]
That's odd, might be a problem with how we use the Windows indexer.

**Comment by RG007JM** [comment]
I just built the app from the release_vnext, and I noticed how a part of the app was able to grab the info from the tag, and also the lyrics! Both ID3V2.x and FLAC work(w/lyrics).
![image](https://user-images.githubusercontent.com/53452689/223869323-fd4de121-100c-4a27-883a-703e1c85e657.png)
![image](https://user-images.githubusercontent.com/53452689/223869364-4ba62f4a-2157-41ee-85bb-6a815802034f.png)

**Comment by itsWindows11** [comment]
I see, lyrics are retrieved from Musixmatch so it isn't related to the music file's properties (at least for now)

**Comment by itsWindows11** [comment]
@RG007JM should be fixed now, try pulling and building again.

**Comment by RG007JM** [comment]
So... It does work-ish, the app breaks at the end of the scan, but I could see from the Album tab that it was recognizing the albums. (It also recognizes 
The first run was from VS2022, the other runs are from the Deployed version.
![Screenshot 2023-03-09 162737](https://user-images.githubusercontent.com/53452689/224074292-f5797c15-5cda-43bb-9e25-5d734b882e82.png)
![Screenshot 2023-03-09 163212](https://user-images.githubusercontent.com/53452689/224074404-fefaf722-4a42-4fcf-85ed-9dca82d6ce20.png)
![Screenshot 2023-03-09 163131](https://user-images.githubusercontent.com/53452689/224074522-9ec7bd15-1642-4beb-a9e9-3971ae4c491a.png)
![Screenshot 2023-03-09 163200](https://user-images.githubusercontent.com/53452689/224074506-6e290a39-49a6-4c07-a67e-aafe503bfc49.png)

**Comment by RG007JM** [comment]
It works wonderfully! Finally, I can use this software. Thanks!
