### ISSUE TITLE
Can't install app

### ISSUE THREAD

**Issue by farhan2077** [josephbeattie/Fluent-Media-Player-Dev#223]
### Description

I followed the exact procedure mentioned in the README, but yet could not install the app. Also in the app properties, the signature name was `71DBF32F-E672-41A2-A72F-A610029965F3` not Rise Software.

### Expected behavior

That the app will be installed

### Rise Media Player Version

v0.0.171.0

### Windows Version

Windows 11 Pro 22H2 22621.1344

### Relevant Assets/Logs

```
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)
```

**Comment by itsWindows11** [comment]
Same procedure should work even with that publisher name.

**Comment by farhan2077** [comment]
I have tried multiple times but could not get it to work

**Comment by itsWindows11** [comment]
Ah, might be a problem with the expired certificates.

**Comment by farhan2077** [comment]
Now that you mention it, I remember seeing something about expired certificate. 
![image](https://user-images.githubusercontent.com/32035481/224559598-543135fd-1a1a-419d-b861-f6fe28f82886.png)
So, what should I do now? Is there any workaround? I really want to try this media player.

**Comment by itsWindows11** [comment]
Either you'll have to wait for the new release or build from source.

**Comment by farhan2077** [comment]
Then I will wait for the new release then.

**Comment by Beech0408** [comment]
> I have tried multiple times but could not get it to work

Me too! Did you get this error message? 
![Screenshot (2)-1](https://user-images.githubusercontent.com/118119005/228310948-6591ba20-89e8-4bfb-9a4f-e869b725e108.png)
