### ISSUE TITLE
Windows 11 Compatability

### ISSUE THREAD

**Issue by TechLionDev** [josephbeattie/Fluent-Media-Player-Dev#225]
### What's the Problem?

I Noticed This Note on The README:
> *1 Any Windows device running Windows 10 1903 or later. Windows Mobile/Windows Phone is not supported.*

I Assume This Includes Windows 11 and would be delighted to find a way to use this asthetically pleasing an beautiful peice of software on it.

### Solution/Idea

N/A

### Alternatives

N/A

### Rise Media Player Version

N/A

### Windows Version

Windows 11 Pro Version	22H2 OS build	22621.1265 Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by RG007JM** [comment]
Windows 11 is supported. If you don't like the current release (which is VERY old), you can build yourself a brand new shiny version with Visual Studio (select relese_vnext).

**Comment by TechLionDev** [comment]
Can't Find A Proper Download, MS-Store Says 404

**Comment by TechLionDev** [comment]
Also When I Try To Install Using MSIX The cert expired as of 3/8

**Comment by Lamparter** [comment]
@TechLionDev Please close this issue, it has been resolved.
The devs are evidently aware that the MSIX certificate has expired and a new build is coming. The internal plans for Rise Media Player remain, it is not "dead", in case you were worrying that.
