### ISSUE TITLE
Cerificate expired 

### ISSUE THREAD

**Issue by gautam-kumar-0** [josephbeattie/Fluent-Media-Player-Dev#231]
### Description

Certificate has expired, and app is not installing.

### Expected behavior

update certificate

### Rise Media Player Version

0.0.171.0

### Windows Version

Edition	Windows 11 Home Single Language Version	22H2 Installed on	‎11-‎03-‎2023 OS build	22621.1413 Experience	Windows Feature Experience Pack 1000.22639.1000.0

### Relevant Assets/Logs

<img width="306" alt="Screenshot 2023-04-13 164818" src="https://user-images.githubusercontent.com/127711023/231743119-0bc2496e-5df8-4355-b071-098d273d4c57.png">
<img width="286" alt="Screenshot 2023-04-13 164833" src="https://user-images.githubusercontent.com/127711023/231743134-7c504296-2eb2-462a-a76a-0b96ca81a42c.png">

**Comment by spesmynuts** [comment]
I've also been having the same issue, the fix for installing it doesn't work anymore due to this issue.

**Comment by RedPCat** [comment]
There's currently a way I found to deal with the certificate issue. When you install the certificate, you'll need to set the time back to anywhere **before March 8th, 2023** as that's when the certificate expired.

**Comment by gautam-kumar-0** [comment]
> There's currently a way I found to deal with the certificate issue. When you install the certificate, you'll need to set the time back to anywhere **before March 8th, 2023** as that's when the certificate expired.

This method worked for me, Thanks!
