### ISSUE TITLE
Error building from source vnext

### ISSUE THREAD

**Issue by Crocodile73** [josephbeattie/Fluent-Media-Player-Dev#240]
### Description

I cannot get a release build to compile. In debug mode is fine.

Severity	Code	Description	Project	File	Line	Suppression State
Error		ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x86.microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\x86\ilc\Tools\nutc_driver.exe @"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\obj\x86\Release\ilc\intermediate\MDIL\Rise Media Player.rsp"' returned exit code 255	Rise.App			

Windows 11 22h2

### Steps To Reproduce

build in release mode
build fails everytime with error

### Expected behavior

build successfully and run

### Rise Media Player Version

build as 14-6-2023

### Windows Version

Windows 11 22H2 22621

### Relevant Assets/Logs

n/a

**Comment by Crocodile73** [comment]
Update, the debug build, crashes on launch.

**Comment by yourordinarycat** [comment]
I cannot recreate the crashing in debug thing, do you have more details on that? This probably sounds silly, but uninstalling and reinstalling could help, there's been a lot of changes revolving around app startup, which might've caused some breaking changes that lead to crashes.

The .NET Native thing is strange, could you try compiling from the `ui/now-playing-improvements` branch? That one fails for me as well with a different exit code, using VS2022 and the x64 target. Not sure about `release_vnext`, I'll try looking into it more deeply when I can:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\x64\ilc\Tools\nutc_driver.exe @"D:\Sources\Rise-Media-Player\Rise Media Player Dev\obj\x64\Release\ilc\intermediate\MDIL\Rise Media Player.rsp"' returned exit code -1073741819	Rise.App			
```

Also enable verbose MSBuild output from Tools > Options > Projects and Solutions > Build And Run, Normal verbosity should be good enough but I'd suggest starting with the highest possible one just in case, .NET Native takes very long to compile, wouldn't want you to spend too long on this.

**Comment by Crocodile73** [comment]
Weird I created a new folder and ran from there in debug mode. Built ok. I get the same error message as you on ui now playing improvements channel. Error code 1073741819

6>Task Performance Summary:

6>        0 ms  CreateProperty                             1 calls

6>        0 ms  GetFrameworkPath                           1 calls

6>        1 ms  SetRidAgnosticValueForProjects             1 calls

6>        1 ms  ValidateConfiguration                      1 calls

6>        1 ms  Delete                                     3 calls

6>        1 ms  AssignCulture                              1 calls

6>        1 ms  CombineXmlElements                         3 calls

6>        2 ms  ResolveNonMSBuildProjectOutput             1 calls

6>        2 ms  CheckForDuplicateNuGetItemsTask            1 calls

6>        2 ms  Touch                                      1 calls

6>        2 ms  ValidateAppxManifestItems                  1 calls

6>        2 ms  GetPackageArchitecture                     1 calls

6>        2 ms  GetReferenceNearestTargetFrameworkTask     1 calls

6>        3 ms  CombineTargetFrameworkInfoProperties       3 calls

6>        3 ms  GetRestoreProjectStyleTask                 1 calls

6>        3 ms  GetDefaultResourceLanguage                 1 calls

6>        3 ms  GetAppxBundlePlatforms                     1 calls

6>        4 ms  ExtractStoreAssociationInformation         1 calls

6>        4 ms  AssignProjectConfiguration                 1 calls

6>        4 ms  GetReferenceAssemblyPaths                  1 calls

6>        4 ms  Hash                                       1 calls

6>        4 ms  GenerateMSBuildEditorConfig                1 calls

6>        5 ms  RemoveDuplicateSDKReferences               1 calls

6>        5 ms  GenerateResource                           1 calls

6>        6 ms  FindAppConfigFile                          1 calls

6>        6 ms  XmlPeek                                    1 calls

6>        8 ms  ConvertToAbsolutePath                      5 calls

6>        9 ms  MakeDir                                    5 calls

6>       10 ms  ValidateSigningCertificate                 1 calls

6>       12 ms  GetSdkFileFullPath                         6 calls

6>       12 ms  GenerateProjectArchitecturesFile           1 calls

6>       13 ms  ReadLinesFromFile                          1 calls

6>       14 ms  CreatePriConfigXmlForFullIndex             1 calls

6>       14 ms  ParseILMergeInfoTask                       1 calls

6>       15 ms  IlcMessageTask                             1 calls

6>       20 ms  RemoveDuplicatePriFiles                    1 calls

6>       22 ms  SharedAssemblyApplicabilityVerifierTask    1 calls

6>       23 ms  GetUnionWinmdPropertyValues                1 calls

6>       24 ms  RemoveDuplicates                           2 calls

6>       24 ms  RemoveRedundantCopyLocalItems              1 calls

6>       25 ms  AssignTargetPath                           8 calls

6>       29 ms  ResolveSDKReference                        2 calls

6>       29 ms  Message                                   28 calls

6>       30 ms  CreatePriFilesForPortableLibraries         1 calls

6>       37 ms  WriteLinesToFile                           3 calls

6>       37 ms  ValidateRdXmlTask                          1 calls

6>       48 ms  ResolvePackageFileConflicts                1 calls

6>       61 ms  GetInstalledSDKLocations                   2 calls

6>       67 ms  GetSDKReferenceFiles                       1 calls

6>       73 ms  GetAssemblyIdentity                        3 calls

6>       92 ms  GetSdkPropertyValue                        3 calls

6>       95 ms  FindUnderPath                              3 calls

6>      118 ms  GeneratePriConfigurationFiles              1 calls

6>      164 ms  GetFrameworkSdkPackages                    2 calls

6>      173 ms  RemovePayloadDuplicates                    7 calls

6>      178 ms  ExpandPayloadDirectories                   1 calls

6>      213 ms  ResolveNuGetPackageAssets                  1 calls

6>      322 ms  CallTarget                                15 calls

6>      454 ms  ComputeManagedBinaries                     1 calls

6>     1240 ms  ResolveAssemblyReference                   1 calls

6>     1264 ms  MSBuild                                    5 calls

6>     1522 ms  ResourceHandlingTask                       1 calls

6>     2419 ms  Copy                                       7 calls

6>     2863 ms  ValidateAppxManifest                       1 calls

6>     3532 ms  GenerateProjectPriFile                     1 calls

6>     4162 ms  ExpandPriContent                           2 calls

6>     5300 ms  GenerateAppxManifest                       1 calls

6> [16356](tel:16356) ms Csc 2 calls

6> [91672](tel:91672) ms CompileXaml 2 calls

6> [447382](tel:447382) ms LoggerBasedExecTask 1 calls

6>

6>Build FAILED.

6>

6>"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\Rise.App.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->

6>(_ValidateSigningCertificate target) ->

6>  C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(875,5): warning : Certificate file does not exist: Rise.App_TemporaryKey.pfx

6>

6>

6>"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\Rise.App.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->

6>(_GenerateProjectPriFileCore target) ->

6> GENERATEPROJECTPRIFILE : warning : PRI257: 0xdef00522 - Resources found for language(s) 'en-gb,en-us,af,ar,ar-eg,ca,cs-cz,da,de-de,el,es-es,fi-fi,fr-fr,he-il,hi-in,hu-hu,it-it,ja-jp,ko-kr,nl-nl,no-no,pl-pl,pt-br,pt-pt,ro-ro,ru-ru,sv-se,tr-tr,uk-ua,vi,zh-cn,zh-hans,zh-hant,zh-hk,zh-tw' but no resources found for default language(s): 'en-us'. Change the default language or qualify resources with the default language. http://go.microsoft.com/fwlink/?LinkId=231899

6>

6>

6>"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\Rise.App.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->

6>(_GenerateCurrentProjectAppxManifest target) ->

6>  C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(2771,5): warning APPX0104: Certificate file 'Rise.App_TemporaryKey.pfx' not found.

6> C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(2771,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.

6>

6>

6>"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\Rise.App.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->

6>(BuildNativePackage target) ->

6>  C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'user32.dll!MessageBox' for method 'System.Int32 Deorcify.<Initializer_Utils>FF6D94A455F999489A709C8FB238883785352D90E065016407B757F0A69487A43__NativeMethods.MessageBox(System.IntPtr, System.String, System.String, System.UInt32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.

6>

6>

6>"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\Rise.App.csproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->

6>(BuildNativePackage target) ->

6>  C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Rise-Media-Player-release_vnext\Rise Media Player Dev\obj\x64\Release\ilc\intermediate\MDIL\Rise Media Player.rsp"' returned exit code -1073741819

6>

6>    5 Warning(s)

6>    1 Error(s)

6>

6>Time Elapsed 00:09:42.49

========== Build: 5 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

========== Build started at 11:42 and took 10:[30.191](tel:30.191) minutes ==========
#

**Comment by itsWindows11** [comment]
@Crocodile73 Try pulling the latest changes and rebuild again.
It works on my end after reverting a commit recently.

**Comment by Crocodile73** [comment]
@itsWindows11 Yes it allows the release build now. Have you removed the progress bar for when it's indexing the library? Does the change effect the indexing speed?

**Comment by itsWindows11** [comment]
Alright good, closing now.

As for the progress bar, not yet. It's in another branch right now iirc.
