### ISSUE TITLE
App Installer failed to install package dependencies. Ask the developer for  package. 

### ISSUE THREAD

**Issue by 3052** [josephbeattie/Fluent-Media-Player-Dev#252]
https://github.com/Rise-Software/Rise-Media-Player/releases/tag/v0.0.300.0

**Comment by Lamparter** [comment]
@3052 are you still experiencing this issue?
Please let me know. If you aren't experiencing it anymore, please close the issue.

**Comment by 3052** [comment]
is a new version available?

**Comment by Lamparter** [comment]
Not quite. You can learn how to install the app here: https://github.com/Rise-Software/Rise-Media-Player/issues/261#issuecomment-2425710423

If you get the issue again with the new bundle, please let me know and I will send you the dependencies.

**Comment by 3052** [comment]
I already tested that version - see original comment

**Comment by Lamparter** [comment]
https://github.com/Rise-Software/Rise-Media-Player/issues/261#issuecomment-2425710423 This is a regenerated version. Can you try it? 

Your comment:
> [`v0.0.300.0` (release)](https://github.com/Rise-Software/Rise-Media-Player/releases/tag/v0.0.300.0)

is of a different release.

**Comment by 3052** [comment]
why do you have the same repo twice?

https://github.com/Rise-Software/Rise-Media-Player/releases/tag/v0.0.300.0

https://github.com/RiversideValley/RiseMediaPlayer/releases/tag/v0.0.300.0

**Comment by Lamparter** [comment]
The first one, https://github.com/Rise-Software/Rise-Media-Player/releases/tag/v0.0.300.0, is the old one that causes the error. Unfortunately I do not have the correct permission level to upload a release to this repo, so I had to in a fork: https://github.com/RiversideValley/RiseMediaPlayer/releases/tag/v0.0.300.0
If the one in my fork causes the dependencies error, please tell me.

**Comment by Lamparter** [comment]
@3052 you can download the dependencies [here](https://github.com/RiversideValley/RiseMediaPlayer/releases/download/v0.0.300.0/NETCoreApp.InheritedDependencies.zip) and then install the `.appx` files in the folder appropriate to your CPU build, `x64|x86`. Please note that even though I have sent dependencies for ARM, the msixbundle I sent does not have the configuration for ARM assembly code.
