### ISSUE TITLE
LastFM references cause compiler errors

### ISSUE THREAD

**Issue by GuildOfCalamity** [josephbeattie/Fluent-Media-Player-Dev#259]
### Description

There appear to be many references to LastFM which are causing compiler errors. I'm guessing you'll need to sync your entire project folder/file structure with the repo again.

### Steps To Reproduce

Clone the project and try to compile (main branch)

### Expected behavior

Compiles

### Rise Media Player Version

0.0.300.0

### Windows Version

Windows 10 22H2

### Relevant Assets/Logs

N/A

**Comment by Chudesnov** [comment]
This isn’t a bug, please refer to the [build documentation](https://github.com/Rise-Software/Rise-Media-Player/blob/main-(insider_bloom)/BUILD.md#adding-lastfm-constants) on how to fix the compile errors yourself.

**Comment by Lamparter** [comment]
@GuildOfCalamity this issue is resolved, please close it; it's cluttering the issues page.

**Comment by GuildOfCalamity** [comment]
@Lamparter cluttering? The other 52 aren't?

**Comment by Lamparter** [comment]
> The other 52 aren't?

@GuildOfCalamity lmao you are right. Most shall be resolved soon as they are primarily about the certificate expiring.
