### ISSUE TITLE
Certificate for Alpha 3 release has been expired

### ISSUE THREAD

**Issue by Runa-Chin** [josephbeattie/Fluent-Media-Player-Dev#260]
### Description

Hello,
I'm writing to inform you that the GitHub release for Rise Media Player on Alpha 3 is no longer valid. The certificate trust has expired, and the package needs to be updated to extend the certificate for at least 20 years. I was unable to install it without updated packages. Please update the packages immediately.

### Steps To Reproduce

Nothing to tell it

### Expected behavior

As what I tell in above, update the packages immediately and extend the certificate up to 20 years.

### Rise Media Player Version

Rise Media Player Alpha 3 -  v0.0.300.0

### Windows Version

Windows 11 24H2 26100.1000

### Relevant Assets/Logs

![Screenshot (8)](https://github.com/user-attachments/assets/8483089f-0614-4a29-b032-c1daebff082e)

**Comment by Josh65-2201** [comment]
Right now you can set your system date to before June of this year and it will then allow it to install, you can then set it back after. But I'm pretty sure this app is not getting any development anymore

**Comment by Runa-Chin** [comment]
Did you think it will works?

**Comment by Josh65-2201** [comment]
It did for me

**Comment by rg991** [comment]
> Right now you can set your system date to before June of this year and it will then allow it to install, you can then set it back after. But I'm pretty sure this app is not getting any development anymore

Yep, this trick does the job

**Comment by Runa-Chin** [comment]
Alright @Josh65-2201 @rg991. I guess I should tried it whetever via PowerShell or App Installer when I am offline. Because that trick doesn't work if NTP servers could rearrange the time when I'm online. And I close this because no comment from dev team.
