### ISSUE TITLE
UI/UX bug and suggestions

### ISSUE THREAD

**Issue by milindgoel15** [josephbeattie/Fluent-Media-Player-Dev#53]
Bugs:

As of pre-alpha 2+, I found some Ui bug in the settings screen. the recent changes when expanded shows a blank box. screenshot below:
![image](https://user-images.githubusercontent.com/45682747/141443935-3d1f40a4-08d7-4c7e-be7b-389ac219f0ed.png)

Not exactly bug:
1. The app size gets high considerably compared to other media players such as music bee. for me, it's about 3GB now. Is this something that will be worked upon in future releases? 
![image](https://user-images.githubusercontent.com/45682747/141444493-bc8a0f58-5f01-4592-b24a-9b96cde1b25d.png)

2. The app reloads and search the entire music database for new media when we reopen the app after putting it into background mode. This could be improved by implementing a button which manually checks for new media instead of doing it automatically on every session reload (or could be a toggle to turn on automatic reloading).

suggestion: 
The mini-player at the bottom keeps on loading and loading until we start playing some media. i would suggest it to display the last played song or hide it all together and only display it when we start to play. 
![image](https://user-images.githubusercontent.com/45682747/141444801-9a1cb988-ff36-4daf-adf8-7eb29a3e5b64.png)

**Comment by itsWindows11** [comment]
> suggestion:
The mini-player at the bottom keeps on loading and loading until we start playing some media. i would suggest it to display the last played song or hide it all together and only display it when we start to play.
image

That "mini-player" will get improved with fresh new code, it will have a new UI and will hide automatically if there's nothing being currently played.

note: I'm currently working on this

**Comment by milindgoel15** [comment]
Cool

**Comment by dlphesigns** [comment]
Now Playing is getting a big update in the next builds, so that should be fixed by then 👀

**Comment by itsWindows11** [comment]
Now playing bar loading issue is fixed in commit 3be368e, this commit also introduces the new now playing bar.

And there is now a "re-scan media" button in the menu flyout when you click on the 3 dots in the titlebar, still there is automatic reloading.

**Comment by milindgoel15** [comment]
Cool
