### ISSUE TITLE
No playing file info 

### ISSUE THREAD

**Issue by iseeghosts** [josephbeattie/Fluent-Media-Player-Dev#54]
I should be able to see what song is playing, but only track length is showing up

**Comment by josephbeattie** [comment]
this is the old now playing bar. the new now playing bar, with song title, is coming in a future update. this is normal behaviour and has been mentioned many times.

**Comment by dlphesigns** [comment]
Now Playing is getting a big update in the next builds, so that should be fixed by then 👀
