### ISSUE TITLE
Crash a few seconds after initial setup completes. Then persists after reopening, can't press any buttons either. (Windows 11 build 22504)

### ISSUE THREAD

**Issue by Somdud111** [josephbeattie/Fluent-Media-Player-Dev#56]

**Comment by Somdud111** [comment]
![image](https://user-images.githubusercontent.com/57676334/142520908-0676589d-d26a-47c8-ab74-3eb503fb64dc.png)
![image](https://user-images.githubusercontent.com/57676334/142520910-5b3e6622-8ba7-41a0-a2ff-9264f998f0b1.png)

**Comment by itsWindows11** [comment]
It seems more like a Windows-related issue looking at the logs, can you debug the app?

**Comment by Somdud111** [comment]
Not sure what happened, but Discy in the Discord gave me a newer build to try in Visual Studio, didn't crashed whatsoever.(although it has some troubles recognizing local music metadata/tags, but it happened on all UWP music programs but not classic x86 programs, so this one is on my end probably).

**Comment by itsWindows11** [comment]
@Somdud111 does pre alpha 3 work for you now?
