### ISSUE TITLE
Facing app crash issue, every time when I try to launch a .mp3 file with it.

### ISSUE THREAD

**Issue by TheNonSmoker** [josephbeattie/Fluent-Media-Player-Dev#62]
Hello! I'm on the version 0.0.12.0 (current latest), and facing the issue of crashing, the app is crashing every time when I try to play a .mp3 (audio) files on it.
Here is a visual representation of the issue ⬇ 

https://user-images.githubusercontent.com/30073064/144041673-9ef20e43-746c-499d-bde5-5b6417a69aac.mp4

**Comment by itsWindows11** [comment]
Currently, Rise Media Player locates the file **only if it's indexed in the app!**, so expect bugs on that part for unindexed files until this behavior changes.

Try moving your music file in a folder where songs get indexed.

**Comment by TheNonSmoker** [comment]
Ohk! 😕
Well, can you tell, will this app in future be able to streaming music online or not?!

**Comment by itsWindows11** [comment]
> Ohk! 😕 Well, can you tell, will this app in future be able to streaming music online or not?!

Ask the devs on discord, I can't really provide much of an answer but all I can say is that there might be online music/video streaming.

**Comment by Windows11-Pro-Ultimate** [comment]
Yes. It happens with me also. When i play a music which is not in library it crashes. And when i play music that is in the library can play. Please fix it.

Adi Sharma.

**Comment by TheNonSmoker** [comment]
> > Ohk! 😕 Well, can you tell, will this app in future be able to streaming music online or not?!
> 
> Ask the devs on discord, I can't really provide much of an answer but all I can say is that there might be online music/video streaming.

Discord link?

**Comment by itsWindows11** [comment]
https://discord.gg/z3Jyqt3BDF

**Comment by TheNonSmoker** [comment]
Thanks.

**Comment by itsWindows11** [comment]
Fixed in latest commit ([c03edc5](https://github.com/Rise-Software/Rise-Media-Player/commit/c03edc5a803434711d1777bc7d8247e08bce5adb))
