### ISSUE TITLE
Download button on main page leads to 404 error

### ISSUE THREAD

**Issue by zephiii** [josephbeattie/Fluent-Media-Player-Dev#68]
**DISCLAIMER: This does not affect the downloads in "Releases". It only affects the main Download button on the main page.**

The Download button on the main page leads to the wrong link.

The link it goes to: https://github.com/Rise-Software/Rise-Media-Player/releases/download/v0.0.13.0/Rise.App_0.0.13.0_x86_x64_arm.msixbundle
The link it should go to: https://github.com/Rise-Software/Rise-Media-Player/releases/download/v0.0.13.0/Rise.App_0.0.13.0_x86_x64_arm_arm64.msixbundle

The missing "_arm64" makes the link invalid.

**Comment by itsWindows11** [comment]
What main page? You mean the readme?

**Comment by itsWindows11** [comment]
Nevermind, knew it, now I gotta close this issue
