### ISSUE TITLE
Music has a lot of stutters

### ISSUE THREAD

**Issue by bevynfernandes** [josephbeattie/Fluent-Media-Player-Dev#69]
When I play music on Pre-Alpha 3, it stutters a lot, and when I used Groove, there were no stutters.

**Comment by itsWindows11** [comment]
Is it resolved in latest release?

**Comment by itsWindows11** [comment]
Is it resolved by latest release?

**Comment by bevynfernandes** [comment]
Yep, not sure what fixed it but it works now. Thanks!

**Comment by itsWindows11** [comment]
I see, you're welcome.
