### ISSUE TITLE
Add an option to disable/control periodical indexing

### ISSUE THREAD

**Issue by alessandrocaseti** [josephbeattie/Fluent-Media-Player-Dev#74]
It's great to have a period indexing but for people that don't download too much music it may be a bit frustrating. My suggestion is to add an option to turn it completely off or decide after how many minutes/hours scan for new files. (Es. 15 Mins, 30 Min, 1hr, 5hrs, Never)

**Comment by esibruti** [comment]
@itsWindows11 This feature has already been added, right?
