### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by thepwrtank18** [josephbeattie/Fluent-Media-Player-Dev#77]
```
App installation failed with error message: Deployment Add operation with target volume C: on Package 71DBF32F-E672-41A2-A72F-A610029965F3_0.0.13.0_neutral_~_cq305awtse1e6 from:  (Rise.App_0.0.13.0_x86_x64_arm_arm64.msixbundle)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)
```

The link doesn't have the error code shown above documented.

**Comment by tylvn** [comment]
![image](https://user-images.githubusercontent.com/95011132/145252168-cc24009d-af2f-4e48-a2b7-548bf83c41d5.png)
I don't know how to add a trusted certificate signature.

**Comment by itsWindows11** [comment]
@qier19 the install instructions, along with how to install the certificate is [here](https://github.com/Rise-Software/Rise-Media-Player#msix-install-instructions)

**Comment by esibruti** [comment]
@itsWindows11 I think we can close this issue

**Comment by itsWindows11** [comment]
Please don't try to handle this yourself, we do manage these issues ourselves, but thanks for pointing these out!
