### ISSUE TITLE
Window Icons are Black in Dark Mode

### ISSUE THREAD

**Issue by Jelly063** [josephbeattie/Fluent-Media-Player-Dev#79]
![image](https://user-images.githubusercontent.com/80640679/145110277-f5b8454a-1d01-4e29-ab8a-a95b88634a3f.png)
The icons at the top right of the window stay black even in Dark Mode, making them difficult to see.

![image](https://user-images.githubusercontent.com/80640679/145110494-4c64ed71-25b1-49ee-9d46-0cd78117f432.png)
The back arrow in the upper left corner of the window is also black in dark mode (or rather dark gray), which means that it is not easy to see either.

**Comment by itsWindows11** [comment]
Not a Rise Media Player issue from what I see.

The first one is a bug in how Windows 11 handles windowing in UWP apparently.

Also, that back button is just disabled, if you navigate to another page then it will be enabled.
