### ISSUE TITLE
Hard-coded version string

### ISSUE THREAD

**Issue by somnisomni** [josephbeattie/Fluent-Media-Player-Dev#85]
There is a hard-coded version string [named `More_Subtitle` in About string resource](https://github.com/Rise-Software/Rise-Media-Player/blob/caa09ec690f3e73e24aaab710d7f92066b13a543/Rise%20Media%20Player%20Dev/Strings/en-gb/About.resw#L147). Since the hard-coding is [not a good practice](https://labs.tadigital.com/index.php/2018/02/22/best-practices-to-avoid-hard-coding-in-net/), even if that is only for devs, I recommend you to use **formatting** instead hard-code version string. maybe it can formatted with `AssemblyVersion` or else...?

Hard-coding version string also can make additional dirty changes **everytime the program version changes**, if the program gets more language. So fixing this will prevent this problem later.

**Comment by josephbeattie** [comment]
Thank you for this. Remember you can always code anything you want to, and submit a PR!

**Comment by somnisomni** [comment]
I'm just browsing the project repository on my phone ;) Thanks for remind, maybe I can make translation to my home language later. This project seems very cool 👍

**Comment by itsWindows11** [comment]
> I'm just browsing the project repository on my phone ;) maybe I can make translation to my home language later. This project seems very cool 👍

Note though, the strings aren't 100% done yet so put that in mind.

**Comment by josephbeattie** [comment]
Yeah. They’re not done in the slightest. :)

**Comment by itsWindows11** [comment]
Should be fixed now.

BTW Crowdin translations are now open on https://crowdin.com/project/rise-media-player, so you can contribute your translations more easily.
