### ISSUE TITLE
App crashing when clicking on About option in settings

### ISSUE THREAD

**Issue by sametaor** [josephbeattie/Fluent-Media-Player-Dev#91]
The app crashes when the About option in the setting panel is clicked on, with a brief glimpse of the about page, and then it immediately crashes.
Steps to Reproduce:
Go to Settings>About
Expected Result:
Shows the About page
Actual Result:
Shows a glimpse of the About page, then crashes
Crash Report:
> The exception Windows.UI.Xaml.Markup.XamlParseException happened last time the app was launched.

>Stack trace:
>XAML parsing failed.

>Source: 
>HResult: -2144665590

**Comment by esibruti** [comment]
@itsWindows11 This issue is already resolved.
