### ISSUE TITLE
RiseMP needs a click to be brought into focus when first opened

### ISSUE THREAD

**Issue by LolicoreExpress** [josephbeattie/Fluent-Media-Player-Dev#93]
When you open up RiseMP, elements aren't hoverable nor clickable. You need to click once somewhere in the window to bring thing "into focus" and for elements to be clickable.

**Comment by itsWindows11** [comment]
That's because of that "indexed songs" notification, it's light dismissable so you would need to click anywhere, I've tried to change it but somehow it got reverted.

**Comment by LolicoreExpress** [comment]
Ahh, right. I didn't even think of that.

**Comment by itsWindows11** [comment]
fixed.
