### ISSUE TITLE
Not sure the reason why it's crashing

### ISSUE THREAD

**Issue by HuyHung1408** [josephbeattie/Fluent-Media-Player-Dev#95]
Stack trace:
Object reference not set to an instance of an object.
   at Rise.App.App.<OnSuspending>d__55.MoveNext() + 0x6e
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33

Source: 
HResult: -2147467261

**Comment by itsWindows11** [comment]
Can you include more details on what happened, what feature that has this problem and what did you do before it crashed?

**Comment by HuyHung1408** [comment]
Rise Media Player is playing a song, and I switch from light mode to dark mode. It freezes for a second then crashes. I think it maybe crash randomly because when I tried to recreate the crash, it does not crash anymore.

**Comment by itsWindows11** [comment]
> Rise Media Player is playing a song, and I switch from light mode to dark mode. It freezes for a second then crashes. I think it maybe crash randomly because when I tried to recreate the crash, it does not crash anymore.

Okay then I'll close the issue, this doesn't seem to be a problem in our end
